[build]
builder = "NIXPACKS"

[deploy]
releaseCommand = "python manage.py migrate --no-input && python manage.py collectstatic --no-input"
startCommand = "gunicorn fitnessPlatform.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
restartPolicyType = "ON_FAILURE"
