# Generated by Django 5.2.11 on 2026-02-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "exercise_type",
                    models.CharField(
                        help_text="Type of exercise for this slot", max_length=50
                    ),
                ),
                (
                    "required_tags",
                    models.JSONField(default=list, help_text="Required exercise tags"),
                ),
                ("sets", models.IntegerField(default=3)),
                ("reps", models.IntegerField(default=12)),
                ("rest_seconds", models.IntegerField(default=60)),
                ("order", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "db_table": "template_slots",
                "ordering": ["order"],
            },
        ),
    ]
