# Generated by Django 5.2.11 on 2026-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(default=list, help_text="List of exercise tags"),
                ),
                (
                    "contraindications",
                    models.JSONField(
                        default=list, help_text="List of contraindications"
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(default=list, help_text="Required equipment"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "exercise_tags",
                "ordering": ["name"],
            },
        ),
    ]
