# Generated by Django 5.2 on 2026-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment Protocol"),
                    ("workout", "Workout Exercise"),
                ],
                default="workout",
                help_text="Assessment Protocol exercises teach users how to perform & score FMS movements. Workout exercises are for program delivery.",
                max_length=20,
            ),
        ),
    ]
