# Generated by Django 5.2 on 2026-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="active_leg_raise_score",
            field=models.IntegerField(default=0, help_text="Active straight leg raise"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="bmi",
            field=models.FloatField(blank=True, help_text="Body Mass Index", null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="cardio_endurance_score",
            field=models.IntegerField(
                default=0, help_text="Cardio endurance test score (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="core_strength_score",
            field=models.IntegerField(
                default=0, help_text="Core strength score (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="fitness_score",
            field=models.IntegerField(
                blank=True, help_text="Overall fitness score (0-100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="flexibility_score",
            field=models.IntegerField(default=0, help_text="Flexibility score (0-10)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="hurdle_step_score",
            field=models.IntegerField(default=0, help_text="Hurdle step assessment"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="inline_lunge_score",
            field=models.IntegerField(default=0, help_text="In-line lunge assessment"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="lower_body_strength_score",
            field=models.IntegerField(
                default=0, help_text="Lower body strength score (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="medical_clearance",
            field=models.BooleanField(
                default=False, help_text="Has medical clearance from doctor if required"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="overhead_squat_score",
            field=models.IntegerField(default=0, help_text="Overhead squat assessment"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="par_q_responses",
            field=models.JSONField(
                default=dict,
                help_text="PAR-Q (Physical Activity Readiness Questionnaire) responses",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="push_up_score",
            field=models.IntegerField(default=0, help_text="Push-up assessment"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="resting_heart_rate",
            field=models.IntegerField(
                blank=True, help_text="Resting heart rate (bpm)", null=True
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="rotary_stability_score",
            field=models.IntegerField(
                default=0, help_text="Rotary stability assessment"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="shoulder_mobility_score",
            field=models.IntegerField(
                default=0, help_text="Shoulder mobility assessment"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="upper_body_strength_score",
            field=models.IntegerField(
                default=0, help_text="Upper body strength score (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="workout_location",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("gym", "Gym"),
                    ("outdoor", "Outdoor"),
                    ("mixed", "Mixed"),
                ],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="years_training",
            field=models.IntegerField(
                default=0, help_text="Years of training experience"
            ),
        ),
    ]
