# Generated by Django 5.2 on 2026-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0002_assessment_active_leg_raise_score_assessment_bmi_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="active_leg_raise_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="age",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="bmi",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="cardio_endurance_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="core_strength_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="experience_level",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="fitness_goals",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="fitness_level",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="fitness_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="flexibility_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="height",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="hurdle_step_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="injuries",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="inline_lunge_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="lower_body_strength_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="medical_clearance",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="overhead_squat_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="par_q_responses",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="push_up_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="resting_heart_rate",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="rotary_stability_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="shoulder_mobility_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="upper_body_strength_score",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="workout_location",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="years_training",
        ),
        migrations.AddField(
            model_name="assessment",
            name="ankle_dorsiflexion",
            field=models.IntegerField(
                default=0, help_text="Ankle Dorsiflexion Knee-to-Wall (0-3)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessment_score",
            field=models.IntegerField(
                default=0, help_text="Movement assessment total (0-30)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="back_status",
            field=models.CharField(
                choices=[
                    ("none", "No issue"),
                    ("past", "Past resolved"),
                    ("mild", "Mild discomfort"),
                    ("moderate", "Moderate pain"),
                    ("severe", "Severe/diagnosed"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="clock_steps",
            field=models.IntegerField(default=0, help_text="Clock Steps (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="competency_label",
            field=models.CharField(
                choices=[
                    ("rebuild", "Rebuild"),
                    ("foundation", "Foundation"),
                    ("build", "Build"),
                    ("perform", "Perform"),
                ],
                default="rebuild",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="competency_level",
            field=models.IntegerField(default=1, help_text="Competency level (1-4)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="composite_score",
            field=models.FloatField(
                default=0, help_text="Weighted composite score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="current_activity_level",
            field=models.IntegerField(
                default=0, help_text="Current activity level (0-4)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="equipment_access",
            field=models.IntegerField(default=0, help_text="Equipment access (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="flag_count",
            field=models.IntegerField(
                default=0, help_text="Number of injury flags (moderate pain)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="front_back_lunges",
            field=models.IntegerField(default=0, help_text="Front/Back Lunges (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="glp1_usage",
            field=models.CharField(
                choices=[
                    ("none", "No"),
                    ("recent", "Recently started"),
                    ("longterm", "Long-term use"),
                ],
                default="none",
                help_text="GLP-1 medication usage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="gym_confidence",
            field=models.IntegerField(default=0, help_text="Gym confidence (0-4)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="hip_status",
            field=models.CharField(
                choices=[
                    ("none", "No issue"),
                    ("past", "Past resolved"),
                    ("mild", "Mild discomfort"),
                    ("moderate", "Moderate pain"),
                    ("severe", "Severe/diagnosed"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="knee_status",
            field=models.CharField(
                choices=[
                    ("none", "No issue"),
                    ("past", "Past resolved"),
                    ("mild", "Mild discomfort"),
                    ("moderate", "Moderate pain"),
                    ("severe", "Severe/diagnosed"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="lateral_load",
            field=models.IntegerField(default=0, help_text="Lateral Load (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="overhead_squat",
            field=models.IntegerField(default=0, help_text="Arms Overhead Squat (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="plank_hold",
            field=models.IntegerField(default=0, help_text="Plank Hold (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="primary_goal",
            field=models.IntegerField(
                default=0, help_text="Primary fitness goal (0-5)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="push_up",
            field=models.IntegerField(
                default=0, help_text="Push-Up Elevated Allowed (0-3)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="questionnaire_score",
            field=models.IntegerField(
                default=0, help_text="Questionnaire total (0-27 actual max for 7 fields)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="readiness_fatigue",
            field=models.IntegerField(
                default=0, help_text="Post-activity fatigue level (0-4)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="recovery_score",
            field=models.IntegerField(default=0, help_text="Recovery total (0-12)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="safety_mode_count",
            field=models.IntegerField(
                default=0, help_text="Number of safety flags (severe)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="salute_plank",
            field=models.IntegerField(
                default=0, help_text="Salute Plank Anti-Rotation (0-3)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="shoulder_status",
            field=models.CharField(
                choices=[
                    ("none", "No issue"),
                    ("past", "Past resolved"),
                    ("mild", "Mild discomfort"),
                    ("moderate", "Moderate pain"),
                    ("severe", "Severe/diagnosed"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="single_leg_stand",
            field=models.IntegerField(default=0, help_text="Single Leg Stand (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="sit_to_stand",
            field=models.IntegerField(
                default=0, help_text="Sit-to-Stand Arms Behind Back (0-3)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="sleep_quality",
            field=models.IntegerField(default=0, help_text="Sleep quality hours (0-4)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="stress_level",
            field=models.IntegerField(default=0, help_text="Stress level (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="timeline_urgency",
            field=models.IntegerField(default=0, help_text="Timeline urgency (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="weight_training_experience",
            field=models.IntegerField(
                default=0, help_text="Weight training experience (0-4)"
            ),
        ),
    ]
