# Generated by Django 5.2 on 2026-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_remove_assessment_active_leg_raise_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="ankle_dorsiflexion",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="lateral_load",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="overhead_squat",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="salute_plank",
        ),
        migrations.AddField(
            model_name="assessment",
            name="deep_squat_hold",
            field=models.IntegerField(
                default=0, help_text="Deep Squat Hold (parallel, heels down) (0-3)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_score",
            field=models.IntegerField(
                default=0, help_text="Movement assessment total (0-21)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="clock_steps",
            field=models.IntegerField(
                default=0, help_text="Clock Steps (2 rounds) (0-3)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="front_back_lunges",
            field=models.IntegerField(
                default=0, help_text="Front/Back Lunges (4 per side) (0-3)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="push_up",
            field=models.IntegerField(default=0, help_text="Push-Ups (max 10) (0-3)"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="sit_to_stand",
            field=models.IntegerField(
                default=0, help_text="Sit-to-Stand (10 reps) (0-3)"
            ),
        ),
    ]
