# Generated by Django 5.2 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_remove_assessment_ankle_dorsiflexion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="ankle_dorsiflexion",
            field=models.IntegerField(
                default=0, help_text="Ankle Dorsiflexion Knee-to-Wall (0-3)"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="lateral_load",
            field=models.IntegerField(default=0, help_text="Lateral Load (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="overhead_squat",
            field=models.IntegerField(default=0, help_text="Arms Overhead Squat (0-3)"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="salute_plank",
            field=models.IntegerField(
                default=0, help_text="Salute Plank Anti-Rotation (0-3)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_score",
            field=models.IntegerField(
                default=0, help_text="Movement assessment total (0-30)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="clock_steps",
            field=models.IntegerField(default=0, help_text="Clock Steps (0-3)"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="deep_squat_hold",
            field=models.IntegerField(
                default=0, help_text="[DEPRECATED] Use overhead_squat instead"
            ),
        ),
    ]
