# Generated by Django 5.2 on 2026-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_assessment_ankle_dorsiflexion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="ankle_dorsiflexion",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="lateral_load",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="overhead_squat",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="salute_plank",
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_score",
            field=models.IntegerField(
                default=0, help_text="Movement assessment total (0-21)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="clock_steps",
            field=models.IntegerField(
                default=0, help_text="Clock Steps (2 rounds) (0-3)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="deep_squat_hold",
            field=models.IntegerField(
                default=0, help_text="Deep Squat Hold (parallel, heels down) (0-3)"
            ),
        ),
    ]
