# Generated by Django 5.2 on 2026-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_medications",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of current medications"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="exercise_restrictions",
            field=models.TextField(
                blank=True, help_text="Any doctor-imposed exercise restrictions"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="injuries",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of current or past injuries"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="medical_conditions",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of medical conditions (e.g., diabetes, hypertension)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pain_areas",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of areas with pain or discomfort",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_loss", "Weight Loss"),
                    ("muscle_gain", "Muscle Gain"),
                    ("general_fitness", "General Fitness"),
                    ("rehabilitation", "Rehabilitation"),
                    ("athletic_performance", "Athletic Performance"),
                    ("flexibility", "Flexibility"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workout_duration",
            field=models.IntegerField(
                blank=True, help_text="Preferred workout duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workout_frequency",
            field=models.IntegerField(
                blank=True, help_text="Desired workouts per week", null=True
            ),
        ),
    ]
