# Generated by Django 5.2 on 2026-03-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_exercise_exercise_type"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="competency_level",
            field=models.IntegerField(
                default=1, help_text="User competency at program creation"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="frequency",
            field=models.IntegerField(default=4, help_text="Workouts per week"),
        ),
        migrations.AddField(
            model_name="program",
            name="program_data",
            field=models.JSONField(
                default=dict, help_text="Structured program data with weeks/days"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="template_name",
            field=models.CharField(default="Custom Program", max_length=100),
        ),
        migrations.CreateModel(
            name="ProgramDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(help_text="Day 1-7 of the week")),
                (
                    "focus",
                    models.CharField(
                        default="General",
                        help_text="e.g., Lower Body, Upper Push",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_days",
                "ordering": ["day_number"],
                "unique_together": {("program", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="DayExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Execution order within the day"
                    ),
                ),
                ("sets", models.IntegerField(default=3)),
                ("reps", models.IntegerField(default=12)),
                ("rest_seconds", models.IntegerField(default=60)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="programs.programday",
                    ),
                ),
            ],
            options={
                "db_table": "day_exercises",
                "ordering": ["order"],
            },
        ),
    ]
